Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class AccountController : Controller
    {
        //
        // GET: /Account/

        public ActionResult Login()
        {
            return View();
        }

    }
}

Web/Controllers/ApplyController.cs
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ams.Web;

namespace Web.Controllers
{
    public class ApplyController : Controller
    {
        //
        // GET: /Apply/
        public EmployeeService EmployeeService { get { return new EmployeeService(); } }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Commit()
        {
            return View();
        }

        public ActionResult ChooseShUser()
        {
            string unitId = "3400008888";
            var list = EmployeeService.GetByUnitId(unitId, "");
            var s = this.RenderViewAsString("_ChooseUser", list);
            return Json(s, JsonRequestBehavior.AllowGet);
        }

    }
}

Web/Controllers/AuditController.cs
using Ams;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace Web.Controllers
{
    public class AuditController : Controller
    {
        //
        // GET: /Audit/

        public AuditService AuditService { get { return new AuditService(); } }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(TransMainInfo condition, PagerInfo<TransMainInfo> pgInfo)
        {
            return Json(AuditService.Get(condition, pgInfo), JsonRequestBehavior.AllowGet);
        }


    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Web/Views/Apply/Commit.cshtml
@{
    ViewBag.Title = "Commit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #list th {
        background-color: #ccffff;
        color: #000;
        width: 120px;
    }


    #list td {
        padding: 0px;
        width: 160px;
        text-align: left;
    }

    .td_txt {
        border: 0;
        background: transparent;
        width: 100%;
        height: 100%;
    }

    .td_select {
        border: 1px;
        background: transparent;
        width: 100%;
        height: 100%;
    }
</style>

<table class="table_solid" id="list" border="0" cellspacing="0" style="width:770px;margin-bottom:30px; cursor:initial;">
    <tr>
        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae;">申请人基本信息</td>
    </tr>
    <tr>
        <th>申请人姓名</th>
        <td><input type="text" class="td_txt" /> </td>
        <th>身份证号码</th>
        <td><input type="text" class="td_txt" /></td>
        <th>性别</th>
        <td>
            &nbsp;&nbsp;<input type="radio" name="sex" value="1" />男
            &nbsp;&nbsp;
            <input type="radio" name="sex" value="0" /> 女
        </td>

    </tr>
    <tr>
        <th>民族</th>
        <td><input type="text" class="td_txt" /></td>
        <th>文化程度</th>
        <td>
            <select class="td_select">
                <option value="小学">小学</option>
                <option value="小学">初中</option>
                <option value="小学">高中</option>
                <option value="小学">大专</option>
                <option value="小学">本科</option>
                <option value="小学">研究生</option>
                <option value="小学">博士生</option>

            </select>
        </td>
        <th>婚姻状况</th>
        <td>
            &nbsp;&nbsp;<input type="radio" name="hy" value="未婚" />未婚
            &nbsp;&nbsp;
            <input type="radio" name="hy" value="已婚" /> 已婚
        </td>



    </tr>
    <tr>
        <th>工作单位</th>
        <td><input type="text" class="td_txt" /></td>
        <th>联系电话</th>
        <td><input type="text" class="td_txt" /></td>
        <th>家庭成员数</th>
        <td>
            <input type="text" class="td_txt" />
        </td>

    </tr>
    <tr>
        <th>供养人数</th>
        <td><input type="text" class="td_txt" /></td>
        <th>家庭月收入</th>
        <td><input type="text" class="td_txt" /></td>
        <th>家庭月支出</th>
        <td>
            <input type="text" class="td_txt" />
        </td>

    </tr>

    <tr style="height:90px;">
        <th>申请人简介</th>
        <td colspan="5"><textarea class="td_txt"></textarea></td>
    </tr>
    <tr>
        <th>配偶姓名</th>
        <td><input type="text" class="td_txt" /></td>
        <th>配偶身份证</th>
        <td><input type="text" class="td_txt" /></td>
        <th>工作单位及职务</th>
        <td>
            <input type="text" class="td_txt" />
        </td>

    </tr>
    <tr>
        <th>配偶月收入</th>
        <td><input type="text" class="td_txt" /></td>
        <th>申请人简介及收入情况分析</th>
        <td colspan="3"><textarea class="td_txt"></textarea></td>

    </tr>
    <tr>
        <td colspan="6" style="color: #000; text-align:center;font-weight:bold;height:30px;background-color:#38aeae;">申请借款用途以及来源</td>
    </tr>

    <tr>
        <th>申请原因及用途</th>
        <td colspan="5"><input type="text" class="td_txt" /></td>
    </tr>
    <tr>
        <th>申请金额</th>
        <td><input type="text" class="td_txt" /></td>
        <th>申请期限</th>
        <td><input type="text" class="td_txt" /></td>
        <th>申请利率</th>
        <td>
            <input type="text" class="td_txt" />
        </td>

    </tr>
    <tr>

        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae; ">担保方式</td>
    </tr>

    <tr>
        <th>担保人</th>
        <td><input type="text" class="td_txt" /></td>
        <th>抵押物</th>
        <td><input type="text" class="td_txt" /></td>
        <th>抵押物所有权人</th>
        <td>
            <input type="text" class="td_txt" />
        </td>

    </tr>
    <tr>
        <th>抵押物价值</th>
        <td><input type="text" class="td_txt" /></td>
        <th></th>
        <td></td>
        <th></th>
        <td></td>

    </tr>
    <tr>

        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae;">调查人认为需要说明的其他情况</td>

    </tr>
    <tr>
        <td colspan="6"><textarea class="td_txt"></textarea></td>
    </tr>
    <tr>

        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae;">风险因素分析</td>

    </tr>
    <tr>
        <td colspan="6"><textarea class="td_txt"></textarea></td>
    </tr>
    <tr>

        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae;">风险防范措施</td>

    </tr>
    <tr>
        <td colspan="6"><textarea class="td_txt"></textarea></td>
    </tr>
    <tr>

        <td colspan="6" style="color: #000; text-align: center; font-weight: bold; height: 30px; background-color: #38aeae;">调查人声明与保证</td>

    </tr>
    <tr style="height:90px;">
        <td colspan="6" style=" text-indent:2em"> 我们对借款申请人进行了调查，遵循客观性原则完成了本报告的撰写，我们对调查报告及附表所陈述事实和数据的真实性承担责任。</td>
    </tr>
    <tr>
        <th>审核人</th>
        <td colspan="4" style="text-align:center;height:50px;">
            <input type="text" name="tags" id="tags" value="" />
        </td>
        <td style="text-align:center; width:100px;"><button class="bgbutton" id="btnChooseUser">选择</button></td>
    </tr>
    <tr>
        <td colspan="6" style="text-align:center;height:50px;">
            <input type="button" value="提交" class="bgbutton" style="width:140px; height:40px;" />
        </td>
    </tr>
</table>
@section headscripts{
    <script src="~/Scripts/taginput/jquery.tagsinput.min.js"></script>
    <link href="~/Scripts/taginput/jquery.tagsinput.min.css" rel="stylesheet" />
}
<script type="text/javascript">

    var userIds = new Array();
    var userNames = new Array();
    //清空用户选择记录
    function cleareChoise() {
        $('#tags').importTags('');
        userIds = new Array();
        userNames = new Array();
    }

    function addUser(id, name) {
        if ($.inArray(id, userIds) == -1) {
            userIds.push(id);
            userNames.push(name);
            $('#tags').addTag(name);
        }
    }

    function removeUser(id, name) {
        if ($.inArray(id, userIds) != -1) {
            userIds.pop(id);
            userNames.pop(name);
            $('#tags').removeTag(name);
        }
    }

    $(function () {
        $('#tags').tagsInput({
            width: 'auto',
            height: '40px',
            onRemoveTag: function (tag) {
                var i = userNames.indexOf(tag);
                var id = userIds[i];
                removeUser(id, tag);
            },
            interactive: false
        });

        $("#btnChooseUser").click(function () {
            $.ajax({
                type: "Get",
                url: '@Url.Action("ChooseShUser")',
                dataType: "json",
                success: function (result) {
                    $("#dialog").html(result).dialog({
                        title: "人员列表",
                        width: 450,
                        maxHeight: 500,
                        resizable: true,
                        modal: true,
                    });
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("获取数据异常：" + errorThrown);
                }
            });
        })
    })
</script>


Web/Views/Apply/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    #list th {
        background-color: #ccffff;
        color: #000;
    }

    #list td {
        padding: initial;
    }

    #list input {
        border: 0;
        background: transparent;
        width: 100%;
        height: 100%;
    }
</style>
<table class="table_solid" id="list" border="0" cellspacing="0" style="width:100%">
    <tr>
        <th>申请人姓名</th>
        <td><input type="text" /> </td>
        <th>身份证号码</th>
        <td>111</td>
        <th>性别</th>
        <td>111</td>
        <th>民族</th>
        <td>111</td>
    </tr>
    <tr>
        <th>申请人姓名</th>
        <td>111</td>
        <th>身份证号码</th>
        <td>111</td>
        <th>性别</th>
        <td>111</td>
        <th>民族</th>
        <td><button class="bgbutton" id="btnChooseUser">选择审核人</button></td>
    </tr>
</table>
<script type="text/javascript">
    $(function () {
        $("#btnChooseUser").click(function () {
            $.ajax({
                type: "Get",
                url: '@Url.Action("ChooseShUser")',
                dataType: "json",
                success: function (result) {
                    $("#dialog").html(result).dialog({
                        title: "选择审核人",
                        width: 430,
                        maxHeight: 500,
                        resizable: true,
                        modal: true,
                    });
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("获取数据异常：" + errorThrown);
                }
            });
        })
    })
</script>

Web/Views/Audit/Index.cshtml
@{
    ViewBag.Title = "审核列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="search_bar" class="mt10 mb15">
    <div class="box">
        <div class="box_border">
            <div class="box_top"><b class="pl15">查询</b></div>
            <div class="box_center pt10 pb10 pl10">
                查询条件
            </div>
        </div>
    </div>
</div>

<div>
    <table class="table_solid" id="list" border="0" cellspacing="0" style="width:100%">
        <tr>
            <th style="width:60px;">序号</th>
            <th style="">单据</th>
            <th style="width:120px">填单人</th>
            <th style="width:130px">创建时间</th>
            <th style="text-align:left;">状态</th>
            <th style="text-align:left; width:90px;">操作</th>
        </tr>
        <!--ko foreach:dataSource-->
        <tr>
            <td data-bind="text:($root.pageIndex()-1)*10+$index() + 1"></td>
            <td data-bind="text:TransName" style="text-align:left;"> </td>
            <td data-bind="text:CreaterName"></td>
            <td data-bind="text:formatedate(CreateTime)"></td>
            <td data-bind="text:StatuMc"></td>
            <td style="text-align:left;">审核</td>
        </tr>
        <!-- /ko -->
        @*<!--ko if:dataSource()==null||dataSource().length==0-->
            <tr><td class="2">暂无数据</td></tr>
            <!-- /ko -->*@
    </table>
    @Html.Partial("_Pager")
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            var options = {
                defaultOrderBy: "CreateTime",
                isAsc: false,
                //form: { Djh: '', Xdsj: '', Xdsj1: '', },
                urls: {
                    query: '@Url.Action("Search")'
                }
            };
            var vm = new viewModel(options);
            ko.applyBindings(vm);
            vm.search();

            $("#list").tableUI();
        });

    </script>
}

Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Web/Views/Shared/_ChooseUser.cshtml
@model List<ViewModel.Employee>

<div>
    <div style="margin-bottom:10px; text-align:center;">
        <input type="text" class="myinput" autofocus />
        <button class="bgbutton" style="margin-right:5px;">查询</button>
        <button class="bgbutton" style="margin-right:5px;" id="btnOk">确定</button>
    </div>
    <table class="table_solid" id="listuser" border="0" cellspacing="0" style="width:100%">
        <tr>
            <th style="width:60px;"></th>
            <th style="text-align: left;">姓名</th>
            <th style="width: 110px; text-align: left;">岗位</th>

        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td><input type="checkbox" data-userid="@item.Id" /> </td>
                <td style="text-align:left;">@item.Name </td>
                <td style="text-align:left;">@item.Station </td>
            </tr>
        }
    </table>
</div>

<script type="text/javascript">
    $(function () {
        $("#listuser").tableUI();
        $("#btnOk").click(function () {
            cleareChoise();
            $("#listuser tr ").find("input[type=checkbox]:checked").each(function () {
                addUser($(this).attr("data-userid"), $(this).parent("td").next().text());
            })
            $("#dialog").dialog("close");
        })
    });
</script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/css/common.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <link href="~/Content/jquery/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link href="~/Content/pagination.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery-ui.min.js"></script>

    <script src="~/Scripts/jquery.formatDate.js"></script>
    <script src="~/Scripts/common.js"></script>
   

    <!--table-->
    <link href="~/Scripts/tableui/jquery.tableui.css" rel="stylesheet" />
    <script src="~/Scripts/tableui/jquery.tableui.js"></script>

    <!--knockout-->
    <script src="~/Scripts/jquery.pagination.js"></script>
    <script src="~/Scripts/knockout-2.2.0.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>
    <script src="~/Scripts/viewmodel.js"></script>

    @RenderSection("headscripts", required: false)

    <script src="~/Scripts/jquery.SuperSlide.js"></script>
    <script type="text/javascript">
        $(function () {
            $(".sideMenu").slide({
                titCell: "h3",
                targetCell: "ul",
                defaultIndex: 0,
                effect: 'slideDown',
                delayTime: '500',
                trigger: 'click',
                triggerTime: '150',
                defaultPlay: true,
                returnDefault: false,
                easing: 'easeInQuint',
                endFun: function () {
                    scrollWW();
                }
            });
            $(window).resize(function () {
                scrollWW();
            });

            // 点击选中
            $('.sideMenu ul li').click(function () {
                $('.on').first().removeClass("on");
                $(this).addClass("on");
            })
        });
        function scrollWW() {
            if ($(".side").height() < $(".sideMenu").height()) {
                $(".scroll").show();
                var pos = $(".sideMenu ul:visible").position().top - 38;
                $('.sideMenu').animate({ top: -pos });
            } else {
                $(".scroll").hide();
                $('.sideMenu').animate({ top: 0 });
                n = 1;
            }
        }

        var n = 1;
        function menuScroll(num) {
            var Scroll = $('.sideMenu');
            var ScrollP = $('.sideMenu').position();
            /*alert(n);
            alert(ScrollP.top);*/
            if (num == 1) {
                Scroll.animate({ top: ScrollP.top - 38 });
                n = n + 1;
            } else {
                if (ScrollP.top > -38 && ScrollP.top != 0) { ScrollP.top = -38; }
                if (ScrollP.top < 0) {
                    Scroll.animate({ top: 38 + ScrollP.top });
                } else {
                    n = 1;
                }
                if (n > 1) {
                    n = n - 1;
                }
            }
        }
    </script>
</head>
<body>
    <div class="top">
        <div id="top_t">
            <div id="logo" class="fl"></div>
        </div>
        <div id="side_here">
            <div id="side_here_l" class="fl"></div>
            <div id="here_area" class="fl">当前位置：</div>
        </div>
    </div>
    <div class="side">
        <div class="sideMenu" style="margin:0 auto">
            <h3>申请管理</h3>
            <ul>
                <li class="on">@Html.ActionLink("申请授权", "Commit", "Apply")</li>
                <li>我的申请</li>
            </ul>
            <h3>审核管理</h3>
            <ul>
                <li>@Html.ActionLink("审核列表", "Index", "Audit")</li>
            </ul>
            <h3>归档管理</h3>
            <ul>
                <li>归档查询</li>
            </ul>
        </div>
    </div>
    <div class="main" style="padding:10px;">
        @RenderBody()
    </div>
    <!-- ui-dialog -->
    <div id="dialog"></div>
    <div class="bottom">
        <div id="bottom_bg">版权</div>
    </div>
    <div class="scroll">
        <a href="javascript:;" class="per" title="使用鼠标滚轴滚动侧栏" onclick="menuScroll(1);"></a>
        <a href="javascript:;" class="next" title="使用鼠标滚轴滚动侧栏" onclick="menuScroll(2);"></a>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_Pager.cshtml
<div class="page" data-bind="visible:$root.totalPages()>1">
    <div class="pagecnt"><div id="pagination" class="pagination"></div></div>
    <div class="pageinfo">
        共 <span class="recordcount" data-bind="text:$root.totalCount()"></span> 条记录
        当前第 <span class="recordcount" data-bind="text:$root.pageIndex()"></span> 页/共 <span class="recordcount" data-bind="text:$root.totalPages()"></span> 页
    </div>
</div>